version: "3.9"

services:
  orders-api:
    image: fluffycocount/ozoz-orders:latest
    networks:
      - traefik_proxy
    environment:
      - ASPNETCORE_ENVIRONMENT=Production
      - ConnectionStrings__OrdersDb=Host=orders-postgres;Port=5432;Database=marketplace-orders-db;Username=postgres;Password=postgres
      - ConnectionStrings__Redis=orders-redis:6379,abortConnect=false
      - GrpcServices__Products=https://ozoz-products.highload-study.ru
    deploy:
      replicas: 1
      labels:
        - "traefik.enable=true"
        - "traefik.http.routers.ozoz-orders.rule=Host(`ozoz-orders.highload-study.ru`)"
        - "traefik.http.routers.ozoz-orders.entrypoints=websecure"
        - "traefik.http.routers.ozoz-orders.tls=true"
        - "traefik.http.routers.ozoz-orders.tls.certresolver=letresolver"
        - "traefik.http.services.ozoz-orders.loadbalancer.server.port=8080"

  orders-postgres:
    image: postgres:16-alpine
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: marketplace-orders-db
    networks:
      - orders_network
    volumes:
      - orders_pgdata:/var/lib/postgresql/data

  orders-redis:
    image: redis:7-alpine
    networks:
      - orders_network
    volumes:
      - orders_redisdata:/data

volumes:
  orders_pgdata:
  orders_redisdata:

networks:
  traefik_proxy:
    external: true